spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}
  jpa:
    show-sql: true
    database-platform: ${DATABASE_ORM}
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
  session:
    jdbc:
      table-name: "SPRING_SESSION"
      initialize-schema: always
      schema: classpath:org/springframework/session/jdbc/schema-mysql.sql

server:
  servlet:
    session:
      timeout: 180
oauth2:
  client_secret:
    kakao: ${CLIENT_SECRET_KAKAO}

